### ISSUE TITLE
Yaml-cpp packaged with Hunter does not build on MSVC 15.9

### ISSUE THREAD

**Issue by mdouaihy** [hunter-packages/yaml-cpp#7]
MSVC 15.9 increased its conformance with the C++ standards. Therefore, yaml-cpp needs some code change to make it compile with it
* The packaged Google Test is 1.8.0. It's not compatible with MSVC 15.9. GoogleTest 1.8.1 should be used.
* noexcept is now defined and _NOEXCEPT should not be used anymore. This was already done in the original project https://github.com/jbeder/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79#diff-ba7996b8b0eda7de7855d4cbd5a11393

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
